"""add faculty study_form funding to applications

Revision ID: 5dc533d6df9e
Revises: c5b3dd985dd4
Create Date: 2026-05-15 01:20:41.560710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc533d6df9e'
down_revision: Union[str, None] = 'c5b3dd985dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('faculty', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('study_form', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('funding', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'funding')
    op.drop_column('applications', 'study_form')
    op.drop_column('applications', 'faculty')
    # ### end Alembic commands ###
