"""add reject_reason to documents

Revision ID: 782c2663591b
Revises: 9760e9631a06
Create Date: 2026-06-14 16:33:14.539161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782c2663591b'
down_revision: Union[str, None] = '9760e9631a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('reject_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'reject_reason')
    # ### end Alembic commands ###
