"""add doc_type edu_level to documents

Revision ID: 9760e9631a06
Revises: 5dc533d6df9e
Create Date: 2026-05-15 03:04:14.840327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9760e9631a06'
down_revision: Union[str, None] = '5dc533d6df9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('edu_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'edu_level')
    op.drop_column('documents', 'doc_type')
    # ### end Alembic commands ###
